### ISSUE TITLE
Define deploy semantics

### ISSUE THREAD

**Issue by rexxars** [sanity-io/core#3]
Deploy now works, but it's fairly basic - it expects a built bundle to exist.

* Should we check for the default `dist` folder and if it doesn't exist, prompt to build it?
* Should we have a `--build` flag which first builds then deploys? If so; should the built bundle exist on local filesystem, or should we simply build it to a temporary folder and delete it after upload?

**Comment by skogsmaskin** [comment]
I say always prompt for build before deploying, and build goes to local build folder. It is nice to have it local and be able to inspect it easily in the current editor if needed.

Also, a --build flag which skips the prompt and just builds it before deploy, is nice.

**Comment by rexxars** [comment]
Agree with @skogsmaskin - implemented in 0.0.36
